name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: readmeio/github-readme-sync@c6e52d127a92145c2aef0a7337f3718a57ac56c4 # 2.0.0
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}

          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './openapi.json'
          api-version: 'v3.0.3'
