name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: readmeio/github-readme-sync@e3e7be426a70b10265e9dd0770652f173cc34d60 # 2.1.3
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}

          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './openapi.json'
          api-version: 'v3.0.3'
